on:
  schedule:
  - cron:  "*/8 * * * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://${{ secrets.TOKEN }}@github.com/Github-Api-master/Source-Repo"
        source_branch: "*"
        destination_repo: "https://${{ secrets.TOKEN }}@github.com/Organization-sync/Dest-Repo"
        destination_branch: "*"